task:
  name: "Surya"
  trigger_type: manual
  timeout_in: 1h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G
      
  setup_script:
    - ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date    
    - pacman -Sy --needed --noconfirm archlinux-keyring
    - pacman -Syyu --needed --noconfirm wget xmlto base-devel inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz git python zip fortune-mod
    - cd ksunongki
    - git submodule update --init --recursive --remote
    - git rev-list --count HEAD
    - cd ..

  Build_script:
      - bash neutron.sh
      
